### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by JimmyEyeball** [unknownskl/xbox-smartglass-core-node#14]
Hi Guys not having no luck with this one at all have updated to 0.4.0 then when I update plugin to 0.10.2   I am getting this constantly..... 

 raspberrypi homebridge[321]: (node:321) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_timeout listeners added. Use emitter.setMaxListeners() to increase limit

Then if I turn an XBOX  off/on once or twice im getting.......

 [4/27/2019, 10:40:33 PM] TypeError: this._socket.send is not a function
Apr 27 22:40:33 raspberrypi homebridge[321]:     at Object._send (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/smartglass.js:221:26)
Apr 27 22:40:33 raspberrypi homebridge[321]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/smartglass.js:100:22)
Apr 27 22:40:33 raspberrypi homebridge[321]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/smartglass.js:144:25)
Apr 27 22:40:33 raspberrypi homebridge[321]:     at EventEmitter.emit (events.js:194:15)
Apr 27 22:40:33 raspberrypi homebridge[321]:     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/events.js:50:23)
Apr 27 22:40:33 raspberrypi homebridge[321]:     at EventEmitter.emit (events.js:189:13)
Apr 27 22:40:33 raspberrypi homebridge[321]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/smartglass.js:197:33)
Apr 27 22:40:33 raspberrypi homebridge[321]:     at Socket.emit (events.js:189:13)
Apr 27 22:40:33 raspberrypi homebridge[321]:     at UDP.onMessage [as onmessage] (dgram.js:628:8)
Apr 27 22:40:33 raspberrypi homebridge[321]: [4/27/2019, 10:40:33 PM] Got SIGTERM, shutting down Homebridge...
Apr 27 22:40:33 raspberrypi homebridge[321]: [4/27/2019, 10:40:33 PM] TypeError: Cannot read property '_crypto' of undefined
Apr 27 22:40:33 raspberrypi homebridge[321]:     at Object.unpack (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/packet/simple.js:145:48)
Apr 27 22:40:33 raspberrypi homebridge[321]:     at Object.unpack (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/packet/packer.js:48:30)
Apr 27 22:40:33 raspberrypi homebridge[321]:     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/events.js:9:28)
Apr 27 22:40:33 raspberrypi homebridge[321]:     at EventEmitter.emit (events.js:189:13)
Apr 27 22:40:33 raspberrypi homebridge[321]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/smartglass.js:197:33)
Apr 27 22:40:33 raspberrypi homebridge[321]:     at Socket.emit (events.js:189:13)
Apr 27 22:40:33 raspberrypi homebridge[321]:     at UDP.onMessage [as onmessage] (dgram.js:628:8)
Apr 27 22:40:38 raspberrypi systemd[1]: homebridgeXbox.service: Main process exited, code=exited, status=143/n/a

**Comment by JimmyEyeball** [comment]
Yeah now after a restart it instance just wont start and is just in a loop with below...


: [4/27/2019, 10:46:00 PM] [Kids Xbox One] Launching app: Dashboard
Apr 27 22:46:00 raspberrypi homebridge[3571]: [4/27/2019, 10:46:00 PM] TypeError: Cannot read property '_crypto' of undefined
Apr 27 22:46:00 raspberrypi homebridge[3571]:     at Object.unpack (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/packet/simple.js:145:48)
Apr 27 22:46:00 raspberrypi homebridge[3571]:     at Object.unpack (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/packet/packer.js:48:30)
Apr 27 22:46:00 raspberrypi homebridge[3571]:     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/events.js:9:28)
Apr 27 22:46:00 raspberrypi homebridge[3571]:     at EventEmitter.emit (events.js:189:13)
Apr 27 22:46:00 raspberrypi homebridge[3571]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/smartglass.js:197:33)
Apr 27 22:46:00 raspberrypi homebridge[3571]:     at Socket.emit (events.js:189:13)
Apr 27 22:46:00 raspberrypi homebridge[3571]:     at UDP.onMessage [as onmessage] (dgram.js:628:8)
Apr 27 22:46:00 raspberrypi homebridge[3571]: [4/27/2019, 10:46:00 PM] TypeError: Cannot read property '_crypto' of undefined
Apr 27 22:46:00 raspberrypi homebridge[3571]:     at Object.unpack (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/packet/message.js:367:34)
Apr 27 22:46:00 raspberrypi homebridge[3571]:     at Object.unpack (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/packet/packer.js:48:30)
Apr 27 22:46:00 raspberrypi homebridge[3571]:     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/events.js:9:28)
Apr 27 22:46:00 raspberrypi homebridge[3571]:     at EventEmitter.emit (events.js:189:13)
Apr 27 22:46:00 raspberrypi homebridge[3571]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/smartglass.js:197:33)
Apr 27 22:46:00 raspberrypi homebridge[3571]:     at Socket.emit (events.js:189:13)
Apr 27 22:46:00 raspberrypi homebridge[3571]:     at UDP.onMessage [as onmessage] (dgram.js:628:8)
Apr 27 22:46:00 raspberrypi homebridge[3571]: [4/27/2019, 10:46:00 PM] Got SIGTERM, shutting down Homebridge...
Apr 27 22:46:00 raspberrypi homebridge[3571]: [4/27/2019, 10:46:00 PM] TypeError: Cannot read property '_crypto' of undefined

**Comment by JimmyEyeball** [comment]
I have 2 Xbox's Running under the 1 instance Should I split them? But they were OK under the previous version 0.10.1...

**Comment by unknownskl** [comment]
Thanks for the bug report! I will look into this soon, probably in 2 weeks due limited time.

**Comment by unknownskl** [comment]
I've been debugging this a bit but it is hard to say where it goes wrong exactly. It could be a combination of the homebridge code and the new release. With only one xbox it works flawless.
I've been trying to connect twice to the same xbox, but it appears that the xbox only responds on one connection.

Try to split it up over 2 homebridge instances. As long i dont have 2 xbox's in one network it is hard to debug this, i'm sorry.

**Comment by unknownskl** [comment]
Please try out the new 0.11.0 version. I think it should work now with multiple xbox's. Can you try?

**Comment by JimmyEyeball** [comment]
Hi Thanks I have had them running on 2 instances and as you say it works flawless other that the instance will crash if you turn the xbox off/on a few times in a row (why you would ever do this normally ) so operating normally no issues 

I will try later and run them on the same instance to see how it goes and report back...

**Comment by JimmyEyeball** [comment]
[5/11/2019, 10:47:55 AM] [Xbox One] Setting Device Power State...
May 11 10:49:20 raspberrypi homebridge[381]: [5/11/2019, 10:49:20 AM] [Xbox One] Setting Device Power State...
May 11 10:49:37 raspberrypi homebridge[381]: [5/11/2019, 10:49:37 AM] [Xbox One] Launching app: Netflix
May 11 10:49:48 raspberrypi homebridge[381]: Failed to connect to xbox: undefined
May 11 10:49:48 raspberrypi homebridge[381]: Failed to connect to xbox: undefined
May 11 10:49:48 raspberrypi homebridge[381]: Failed to connect to xbox: undefined
May 11 10:49:48 raspberrypi homebridge[381]: Failed to connect to xbox: undefined
May 11 10:49:48 raspberrypi homebridge[381]: [5/11/2019, 10:49:48 AM] TypeError: this._socket.send is not a function
May 11 10:49:48 raspberrypi homebridge[381]:     at Object._send (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/smartglass.js:221:26)
May 11 10:49:48 raspberrypi homebridge[381]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/smartglass.js:100:22)
May 11 10:49:48 raspberrypi homebridge[381]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/smartglass.js:144:25)
May 11 10:49:48 raspberrypi homebridge[381]:     at EventEmitter.emit (events.js:194:15)
May 11 10:49:48 raspberrypi homebridge[381]:     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/events.js:50:23)
May 11 10:49:48 raspberrypi homebridge[381]:     at EventEmitter.emit (events.js:189:13)
May 11 10:49:48 raspberrypi homebridge[381]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/smartglass.js:197:33)
May 11 10:49:48 raspberrypi homebridge[381]:     at Socket.emit (events.js:189:13)
May 11 10:49:48 raspberrypi homebridge[381]:     at UDP.onMessage [as onmessage] (dgram.js:628:8)
May 11 10:49:48 raspberrypi homebridge[381]: [5/11/2019, 10:49:48 AM] Got SIGTERM, shutting down Homebridge...
May 11 10:49:48 raspberrypi homebridge[381]: Current active app: Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application
May 11 10:49:48 raspberrypi homebridge[381]: 2
May 11 10:49:48 raspberrypi homebridge[381]: [5/11/2019, 10:49:48 AM] [Xbox One] Launching app: Dashboard
May 11 10:49:53 raspberrypi systemd[1]: homebridgeXbox.service: Main process exited, code=exited, status=143/n/a
May 11 10:49:53 raspberrypi systemd[1]: homebridgeXbox.service: Unit entered failed state.
May 11 10:49:53 raspberrypi systemd[1]: homebridgeXbox.service: Failed with result 'exit-code'.

**Comment by JimmyEyeball** [comment]
That's just testing a Single XBox after the update...

**Comment by JimmyEyeball** [comment]
[5/11/2019, 10:58:36 AM] [Xbox One] Setting Device Power State...
May 11 10:58:36 raspberrypi homebridge[6820]: [5/11/2019, 10:58:36 AM] [Xbox One] 0
May 11 10:58:41 raspberrypi homebridge[6820]: Xbox succesfully connected!
May 11 10:58:52 raspberrypi homebridge[6820]: Failed to connect to xbox: false
May 11 10:59:22 raspberrypi homebridge[6820]: Failed to connect to xbox: false
May 11 10:59:52 raspberrypi homebridge[6820]: Failed to connect to xbox: false
May 11 11:00:22 raspberrypi homebridge[6820]: Failed to connect to xbox: false
May 11 11:00:50 raspberrypi homebridge[6820]: (node:6820) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_console_status listeners added. Use emitter.setMaxListeners() to increase limit
May 11 11:00:52 raspberrypi homebridge[6820]: Failed to connect to xbox: false
May 11 11:01:22 raspberrypi homebridge[6820]: Failed to connect to xbox: false
May 11 11:01:52 raspberrypi homebridge[6820]: Failed to connect to xbox: false
May 11 11:02:20 raspberrypi homebridge[6820]: (node:6820) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_discovery_response listeners added. Use emitter.setMaxListeners() to increase limit
May 11 11:02:20 raspberrypi homebridge[6820]: (node:6820) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_timeout listeners added. Use emitter.setMaxListeners() to increase limit
May 11 11:02:22 raspberrypi homebridge[6820]: Failed to connect to xbox: false
May 11 11:02:52 raspberrypi homebridge[6820]: Failed to connect to xbox: false
May 11 11:03:22 raspberrypi homebridge[6820]: Failed to connect to xbox: false
May 11 11:03:52 raspberrypi homebridge[6820]: Failed to connect to xbox: false

**Comment by unknownskl** [comment]
Are you sure you are running the newer version? The stack trace does tell me it is not using the newest version.

**Comment by unknownskl** [comment]
I've seen this error when missing python + the required dependencies. Please check the readme for the dependencies.
